# Tells Jekyll some basics about this project (e.g. telling Jekyll the name of our site and what version of Markdown we'd like to use)
# Site.<VarName> should reference below values
title: Mox Devs
name: marc ochsner
tagline: christian, husband, father, developer
plugins:
  - jekyll-html-pipeline
  - jekyll-octicons
  - jemoji
markdown: kramdown
permalink: /blog/:year/:month/:day
exclude:
  - "node_modules/*.md"
include:
  - "node_modules"
site_url: https://m.ochs.io 

disqus_shortname: mochsner

# Blog
blog_title: Marc Codes
blog_description: Rambles of developer
blog_url: /posts/

# Syntax
highlighter: rouge


# Categories via Collections https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

## Defaults you can change
## The following defaults are set by GitHub, which you are free to override in your _config.yml file:

#  github: [metadata]
#  encoding: UTF-8
#  kramdown:
#    input: GFM
#    hard_wrap: false
#  future: true
#  jailed: false
#  theme: jekyll-theme-primer
#  gfm_quirks: paragraph_end
# Configuration settings you cannot change

## GitHub Pages & Jekyll override the following settings in your _config.yml file, which you cannot change:
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
kramdown:
#   math_engine: mathjax
   syntax_highlighter: rouge

theme: jekyll-theme-slate