# Tells Jekyll some basics about this project (e.g. telling Jekyll the name of our site and what version of Markdown we'd like to use)
# Site.<VarName> should reference below values
name: Marc Ochsner
blog_title: Marc Ochsner
tagline: Something that makes me sound interesting
plugins:
  - jekyll-html-pipeline
  - jekyll-octicons
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: ["Rakefile"]


## Defaults you can change
## The following defaults are set by GitHub, which you are free to override in your _config.yml file:

#  github: [metadata]
#  encoding: UTF-8
#  kramdown:
#    input: GFM
#    hard_wrap: false
#  future: true
#  jailed: false
#  theme: jekyll-theme-primer
#  gfm_quirks: paragraph_end
# Configuration settings you cannot change

## GitHub Pages & Jekyll override the following settings in your _config.yml file, which you cannot change:
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
